@url = http://localhost:8000

GET {{url}}/hello
###
GET {{url}}/employees
###

GET {{url}}/employees/20f3d3a6d42894d911c7ba6382ccf9da
###

POST {{url}}/employees/
Content-Type: application/json

{
  "name": "Alex",
  "position" : "Developer",
  "salary" : 50000,
  "other" : "Stuff"
}
###



