@url = http://localhost:8000

GET {{url}}/hello
###
GET {{url}}/employees
###

GET {{url}}/employees/eccc1aef2534734f677137965faed187
###

POST {{url}}/employees/
Content-Type: application/json

{
  "name": "Alex",
  "position" : "Scrum Master",
  "salary" : 50000,
  "other" : "Stuff"
}
### good request

POST {{url}}/employees/
Content-Type: application/json

{
  "name": "Alex",
  "position" : "Intern",
  "salary" : 50000,
  "other" : "Stuff"
}
### bad request


